### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by hisea** [alex-cory/use-http#38]
When used with Next.js and trying to reload a page from bowser, get following error:

```
ReferenceError: window is not defined
    at /Users/user/workspace/project1/node_modules/use-http/src/useFetch.ts:61:30
    at useFetch (/Users/user/workspace/project1/node_modules/use-http/src/useFetch.ts:129:27)
    at Reports (/Users/user/workspace/project1/build/server/static/development/pages/reports.js:685:76)
    at processChild (/Users/user/workspace/project1/node_modules/react-dom/cjs/react-dom-server.node.development.js:2888:14)
    at resolve (/Users/user/workspace/project1/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/Users/user/workspace/project1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/Users/user/workspace/project1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Users/user/workspace/project1/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Users/user/workspace/project1/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/user/workspace/project1/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (/Users/user/workspace/project1/build/server/static/development/pages/_document.js:555:41)
    at Object.loadGetInitialProps (/Users/user/workspace/project1/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/user/workspace/project1/node_modules/next-server/dist/server/render.js:218:36)
```

**Comment by alex-cory** [comment]
What version of `use-http` are you using?

**Comment by hisea** [comment]
the latest: `0.1.74`

**Comment by alex-cory** [comment]
🤔ok I will get to this after work today :)

**Comment by alex-cory** [comment]
This fix is done, it's just in a branch with other stuff. I'll pull it out tomorrow morning and get this fix in quick in the AM. If you're curious, [the branch is here](https://github.com/alex-cory/use-http/compare/ssr-fix-and-form-data)

**Comment by alex-cory** [comment]
this should be fixed. I'm going to go ahead and close this.
